initial_layer_infill_speed = "!cap(50)"
sparse_infill_speed = "!cap(120)"
internal_solid_infill_speed = "!cap(80)"
inner_wall_speed = "!cap(120)"
top_surface_speed = "!cap(100)"

# Do not override the VFA speed?
outer_wall_speed = "!cap(80)"

description = """
Speeds from eSUN for their PETG. This can probably be used for anything that needs
to go slower. This is not intended for HS/HF, those can go faster than this."""
