initial_layer_infill_speed = "!cap(50)"
sparse_infill_speed = "!cap(120)"
internal_solid_infill_speed = "!cap(80)"
inner_wall_speed = "!cap(120)"
top_surface_speed = "!cap(100)"

# Do not override the VFA speed?
outer_wall_speed = "!cap(80)"

description = """
Compared to the default, the speeds are adjusted to what eSUN wants for their PETG (not
HS). This can probably be used for anything that needs to go slower."""
