# A very good writeup:
# https://www.reddit.com/r/BambuLab/comments/1aml185/my_conclusions_on_wall_chatter_and_how_to_fix_it/
# TLDR; Pressure advance and flow ratio plays a big role in VFA. The symptoms get worse on
# smaller layer heights. Slower speeds and wider outer walls can help.
# My own experience: different filaments show different amounts of VFA, eSUN PETG+HS shows
# more VFA, on 0.16mm layer height, than eSUN PLA+, but almost nothing on 0.24mm.

# This speed on the outer wall shows the least pronounced Vertical Fine Artifacts. Too low
# and steppers motor artifacts are showing, too high and ghosting starts showing more.
outer_wall_speed = "100"

# Taken from the standard 0.16mm high quality profile. All calibrations, like VFA and PA,
# are done with this acceleration, so all profiles should have the same value to get
# consistent results. I tried with 4000, but that just made the same artifacts pop out
# more.
outer_wall_acceleration = "2000"

# VFA test results on dark blue eSUN PLA+:
# 0.2mm standard with outer wall accel 5000 mm/s^2 and jerk 9 mm/s^3
#   best outer wall: 90-110 mm/s
# 0.16mm high quality with outer wall accel 2000 mm/s^2 and jerk 9 mm/s^3
#   best outer wall: 100-120 mm/s
#   worst outer wall: 60 mm/s and below

# VFA test results on black eSUN PETG+HS:
# 0.16mm high quality with outer wall accel 2000 mm/s^2 and jerk 9 mm/s^3
#   best outer wall: 90-100 mm/s
#   worst outer wall: 60 mm/s and below
#   bad outer wall: 120 mm/s and up

# Match this with the defaults in bambu studio, which greatly reduces ringing artefacts.
inner_wall_acceleration = "!cap(parent(key='default_acceleration'))"
# This is also lowered to not be so ridiculously high
travel_acceleration = "!cap(parent(key='default_acceleration'))"

description = """
Compared to the default bambu profile, it has adjusted speeds and accelerations, tuned to
get the best surface finish on my particular printer."""
