name = "Better PETG"
inherits = "Generic PETG @BBL A1"

# Is 75 because eSUN wants that as minimum
textured_plate_temp = ["75"]
textured_plate_temp_initial_layer = ["75"]
hot_plate_temp = ["75"]
hot_plate_temp_initial_layer = ["75"]

description = """
Supposedly gives better results than the Bambu PETG profiles by having lower max flow
and higher cooling."""

filament_notes = """
https://www.reddit.com/r/BambuLab/comments/1bjnzbp/comment/kvtie09/
https://www.reddit.com/r/BambuLab/comments/18u12ol/comment/kfhgjke/"""
